# Generated by Django 5.2.11 on 2026-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Унікальний ключ, напр. welcome, ask_phone, menu_header",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Назва для адмінки (щоб було зручно шукати)",
                        max_length=120,
                    ),
                ),
                ("text", models.TextField(help_text="Текст повідомлення")),
                (
                    "parse_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("HTML", "HTML"),
                            ("Markdown", "Markdown"),
                        ],
                        default="HTML",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Де використовується / підказка для контент-менеджера",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot message",
                "verbose_name_plural": "Bot messages",
                "ordering": ["key"],
            },
        ),
    ]
