# Generated by Django 5.2.11 on 2026-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="location_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
