# Generated by Django 5.2.11 on 2026-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
