# Generated by Django 5.2.11 on 2026-02-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "full_title",
                    models.CharField(default="Комплекс повністю", max_length=80),
                ),
                ("full_price", models.PositiveIntegerField()),
                (
                    "first_title",
                    models.CharField(default="Перша страва", max_length=80),
                ),
                ("first_price", models.PositiveIntegerField(default=0)),
                (
                    "second_title",
                    models.CharField(default="Друга страва", max_length=80),
                ),
                ("second_price", models.PositiveIntegerField(default=0)),
                (
                    "third_title",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("third_price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "menu_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menuday",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
